---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
         - apache2
         - libapache2-mod-php5 
         - ssh
         - vsftpd
         - dhcpd
     
    - name: ansible create directory with mode setting example
      file:
        path: /etc/firewall
        state: directory
        mode: "u=rw,g=wx,o=rwx"
      become: yes

    - name: ansible create directory with mode setting example
      file:
        path: /home/teste/ftp
        owner: 'nobody'
        group: 'nogroup'
        state: directory
        mode: "u=rx,g=rx,o=rx"
      become: yes

    - name: start apache
      service: name=apache2 state=started enabled=yes
      become: yes
      
    - name: copy firewall
      copy: src=firewall dest=/etc/init.d/firewall mode=+x
      become: yes

    - name: copy firewall.rules 
      copy: src=firewall.rules dest=/etc/firewall/firewall.rules mode=0770
      become: yes

    - name: copy dhcpd
      copy: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf mode=0770
      become: yes

    - name: start firewall
      service: name=firewall state=started enabled=yes
      become: yes
    
    - name: start dhcpd
      service: name=isc-dhcp-server state=started enabled=yes   
      become: yes


    - name: Add user teste
      user:
        name: teste
        comment: "Usuario de teste"
        home: /home/teste
        createhome: yes
        password: '$6$5rfJCWV/$1VLnFeh9pVtLV2K4ei93EuTz0GZKSnNevEaSlKbhnW9P/wtGGcBwDnUMPyrKUprXNebU2XnNCFGq00UEhrdyb0'
        append: yes
      become: yes


