---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
         - apache2
         - libapache2-mod-php5 
         - ssh
         - vsftpd
         - dhcpd
     
    - name: ansible create directory with mode setting example
      file:
        path: /etc/firewall
        state: directory
        mode: "u=rw,g=wx,o=rwx"
      become: yes

    - name: ansible create directory with mode setting example
      file:
        path: /home/teste/ftp
        owner: 'nobody'
        group: 'nogroup'
        state: directory
        mode: "u=rx,g=rx,o=rx"
      become: yes

    - name: start apache
      service: name=apache2 state=started enabled=yes
      become: yes
      
    - name: copy firewall
      copy: src=firewall dest=/etc/init.d/firewall mode=+x
      become: yes

    - name: copy firewall.rules 
      copy: src=firewall.rules dest=/etc/firewall/firewall.rules mode=0770
      become: yes

    - name: copy dhcpd
      copy: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf mode=0770
      become: yes

    - name: start firewall
      service: name=firewall state=started enabled=yes
      become: yes
    
    - name: start dhcpd
      service: name=isc-dhcp-server state=started enabled=yes   
      become: yes


    - name: Add user teste
      user:
        name: teste
        comment: "Usuario de teste"
        home: /home/teste
        createhome: yes
        password: '$6$vLlOsNs0$7xg.kd2DeiTI/kT/dSwB5eUi.FIOH1QawaHYrMWEqmQ0IPD.I15eOo4hexsOlURYZ35LinP75tPztS35HheTJ0'
        append: yes
      become: yes
      
    - name: Configure o vsftp.conf
      replace:
        path: '/etc/vsftpd.conf'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: '#chroot_local_user=YES', value: 'chroot_local_user=YES'}
        - { regex: '#write_enable=YES', value: 'write_enable=YES'}
      become: yes


    - name: Adicionando linhas ao vsftp.conf
      blockinfile:
        path: '/etc/vsftpd.conf'
        block: |
          user_sub_token=$USER
          local_root=/home/$USER/ftp
          pasv_min_port=40000
          pasv_max_port=50000
          userlist_enable=YES
          userlist_file=/etc/vsftpd.userlist
          userlist_deny=NO
        backup: yes
      become: yes

    - name: cria o vsftpd.userlist
      shell: 'echo teste > /etc/vsftpd.userlist'
      become: yes

    - name: start vsftpd
      service: name=vsftpd state=started enabled=yes   
      become: yes




